version: "3.9"

services:
  
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      -  27017

  server:
    container_name: server
    image: hxyro/modifier-server
    build:
      context: ./packages/server/
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - NEXT_PUBLIC_SERVER_URL=localhost
    ports:
      -  80
    depends_on:
      - mongodb
    restart: unless-stopped
  
  app:
    container_name: app
    image: hxyro/modifier-app
    build:
      context: ./packages/app/
      dockerfile: Dockerfile
    ports:
      - 80
    restart: unless-stopped

  nginx-proxy:
    container_name: proxy
    image: hxyro/modifier-nginx-proxy
    build:
      context: ./packages/nginx-proxy/
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - server
      - app
