version: "3.9"

services:
  
  mongodb:
    # container_name: mongodb
    image: mongo
    ports:
      -  27017

  server:
    # container_name: server
    image: hxyro/modifier-server
    build:
      context: ./packages/server/
      dockerfile: Dockerfile
    environment:
      # - MONGODB_HOST=mongodb
      - NEXT_PUBLIC_SERVER_URL=https://nginx-proxy-hxyro.cloud.okteto.net
    ports:
      -  5000
    depends_on:
      - mongodb
    restart: unless-stopped
  
  app:
    # container_name: app
    image: hxyro/modifier-app
    build:
      context: ./packages/app/
      dockerfile: Dockerfile
    ports:
      - 3000
    restart: unless-stopped

  nginx-proxy:
    # container_name: proxy
    image: hxyro/modifier-nginx-proxy
    build:
      context: ./packages/nginx-proxy/
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - server
      - app
