apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.appDeployment.name }}
  namespace: {{ .Values.appDeployment.namespace }}
  labels:
    app: {{ .Values.appDeployment.app }}
spec:
  replicas: {{ .Values.appDeployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appDeployment.app }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.appDeployment.app }}
    spec:
      containers:
      - name:  app
        image:  {{ .Values.appDeployment.image}}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 200Mi
        ports:
        - containerPort: {{ .Values.appDeployment.containerPort}}
      restartPolicy: Always
