apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.serverDeployment.name }}
  namespace: default
  labels:
    app: {{ .Values.serverDeployment.app }}
spec:
  replicas: {{ .Values.serverDeployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.serverDeployment.app }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.serverDeployment.app }}
    spec:
      containers:
      - name:  server
        image:  {{ .Values.serverDeployment.image }}
        imagePullPolicy: {{ .Values.serverDeployment.imagePullPolicy }}
        resources:
          requests:
            cpu: 500m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 200Mi
        env:
        - name:  PORT
          valueFrom:
            configMapKeyRef:
              name:  configmap
              key:  server_port
        - name:  NEXT_PUBLIC_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name:  configmap
              key:  next_public_server_url
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name:  secret
              key:  database_url
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name:  secret
              key:  aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name:  secret
              key:  aws-secret-access-key
        - name: AWS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name:  secret
              key:  aws-bucket-name
        ports:
        - containerPort: {{ .Values.serverDeployment.containerPort }}
      restartPolicy: Always
---

